using Domain.Modules.CatalogSearch.Entities;

namespace Domain.Modules.CatalogSearch.Specifications;

/// <summary>
/// Compiles a list of RuleDefinition objects into a single ISpecification&lt;SearchCriteria&gt;
/// that can be used to evaluate whether a given SearchCriteria satisfies all applicable rules.
/// 
/// This is the core engine behind the data-driven rules approach:
/// instead of hardcoded if/else chains, rules are evaluated dynamically
/// based on their type, parameters, and priority.
/// 
/// Follows Strategy pattern internally — each RuleType is handled by a specialized evaluator.
/// </summary>
public sealed class RuleSpecificationCompiler
{
    /// <summary>
    /// Compiles a list of rules (ordered by effective priority) into a composite specification.
    /// The winning rule (highest effective priority) determines the outcome.
    /// </summary>
    public ISpecification<SearchCriteria> Compile(IReadOnlyList<RuleDefinition> rules)
    {
        return new CompiledRuleSpecification(rules);
    }

    /// <summary>
    /// Internal specification implementation generated by the compiler.
    /// Evaluates rules in priority order against a SearchCriteria candidate.
    /// </summary>
    private sealed class CompiledRuleSpecification : ISpecification<SearchCriteria>
    {
        private readonly IReadOnlyList<RuleDefinition> _rules;

        public CompiledRuleSpecification(IReadOnlyList<RuleDefinition> rules)
        {
            _rules = rules ?? throw new ArgumentNullException(nameof(rules));
        }

        public bool IsSatisfiedBy(SearchCriteria candidate)
        {
            if (_rules.Count == 0)
                return false; // Fail-closed: no rules = not available

            foreach (var rule in _rules) // Already ordered by priority (desc)
            {
                if (RuleMatchesCriteria(rule, candidate))
                {
                    return rule.Effect == Enums.Effect.Allow;
                }
            }

            // No rule matched the criteria — default to deny
            return false;
        }

        /// <summary>
        /// Evaluates whether a rule's parameters match the given search criteria.
        /// Handles different rule types (Weekly, Seasonal, Exception).
        /// </summary>
        private static bool RuleMatchesCriteria(RuleDefinition rule, SearchCriteria criteria)
        {
            return rule.Type switch
            {
                Enums.RuleType.Weekly => EvaluateWeeklyRule(rule, criteria),
                Enums.RuleType.Seasonal => EvaluateSeasonalRule(rule, criteria),
                Enums.RuleType.Exception => EvaluateExceptionRule(rule, criteria),
                _ => false
            };
        }

        private static bool EvaluateWeeklyRule(RuleDefinition rule, SearchCriteria criteria)
        {
            if (!rule.Params.TryGetValue("DaysOfWeek", out var daysObj))
                return true; // No day constraint — rule applies to all days

            if (daysObj is not IEnumerable<DayOfWeek> allowedDays)
                return true;

            var queryDays = GetDaysInRange(criteria.TimeRange);
            return queryDays.All(d => allowedDays.Contains(d));
        }

        private static bool EvaluateSeasonalRule(RuleDefinition rule, SearchCriteria criteria)
        {
            if (!rule.Params.TryGetValue("StartMonth", out var startObj) ||
                !rule.Params.TryGetValue("EndMonth", out var endObj))
                return true; // No season constraint — applies always

            if (startObj is not int startMonth || endObj is not int endMonth)
                return true;

            var queryMonth = criteria.TimeRange.Start.Month;
            return startMonth <= endMonth
                ? queryMonth >= startMonth && queryMonth <= endMonth
                : queryMonth >= startMonth || queryMonth <= endMonth; // Wraps around year boundary
        }

        private static bool EvaluateExceptionRule(RuleDefinition rule, SearchCriteria criteria)
        {
            if (!rule.Params.TryGetValue("Date", out var dateObj))
                return false; // Exception rules must specify a date

            if (dateObj is not DateTime exceptionDate)
                return false;

            return criteria.TimeRange.Contains(exceptionDate);
        }

        private static IEnumerable<DayOfWeek> GetDaysInRange(ValueObjects.DateRange range)
        {
            var days = new HashSet<DayOfWeek>();
            var current = range.Start.Date;
            while (current <= range.End.Date)
            {
                days.Add(current.DayOfWeek);
                current = current.AddDays(1);
            }
            return days;
        }
    }
}
